### ISSUE TITLE
zigen-star.csv 存在废弃字根

### ISSUE THREAD

**Issue by Dieken** [forFudan/yu#6]
https://github.com/forFudan/yu/blob/main/src/public/zigen-star.csv#L308

𮓗

<img width="203" alt="image" src="https://github.com/forFudan/yu/assets/2365/0b9c27b9-d017-4dbe-96da-0ab670f99be2">

这个字根已经废弃了。

另外 「牜」这个根在  https://yuhao.forfudan.com/chaifen.csv 里全用的是「牛」了，是不是去掉算了，反正「足」根也没留「⻊」。

**Comment by forFudan** [comment]
文件裏没有「𮓗」這個字根呀。
